name: Test CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, bootstrap, and test
        run: |
          npm install
          npm run bootstrap
          cd backend
          npm run test
      - name: Getting Code Coverage
        run: |
          npm install -g codecov
          codecov
        env:
          CODECOV_TOKEN: '1be4aaf8-fa5b-44d0-bfe2-17b876ba2cce'
          CI: true
